[project]
name = "kai-graphora"
version = "0.1.0"
description = "Hi! My name is Kai G. I'm a knowledge AI, skilled in vector search, and graph RAG. My DB of choice is SurrealDB."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "pydantic>=2.11.4",
    "sentence-transformers>=4.1.0",
    "surrealdb>=1.0.3",
]

[project.scripts]
cli = "demo:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
venvPath = "."
venv = ".venv"
