[project]
name = "kai-graphora"
version = "0.1.0"
description = "Hi! My name is Kai G. I'm a knowledge AI, skilled in vector search, and graph RAG. My DB of choice is SurrealDB."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.0",
    "pydantic>=2.11.4",
    "sentence-transformers>=4.1.0",
    "surrealdb>=1.0.3",
]

[dependency-groups]
dev = [
    "pyright>=1.1.400",
    "ruff>=0.11.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
surrealdb = { path = "/Users/martin/repos/surrealdb.py", editable = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
line-length = 80
indent-width = 4

[tool.pyright]
venvPath = "."
venv = ".venv"
