[project]
name = "demo-langchain"
version = "0.1.0"
description = "Demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-community",
    "langgraph>=0.4.1",
    "ollama>=0.4.8",
    "langchain-ollama>=0.3.2",
    "langchain-experimental>=0.3.4",
]

[tool.uv.sources]
langchain-community = { path = "/Users/martin/repos/langchain-community/libs/community", editable = true }

[project.scripts]
demo-langchain = "demo_langchain:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
