[project]
name = "demo-vanilla"
version = "0.1.0"
description = "Demo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.0",
    "pydantic>=2.11.4",
    "sentence-transformers>=4.1.0",
    "kai-graphora",
]

[project.scripts]
demo-vanilla = "demo_vanilla:cli"

[tool.uv.sources]
kai-graphora = { workspace = true }

[tool.pyright]
venvPath = "."
venv = ".venv"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
